# Example Site settings

google_analytics: G-FG87FPT3X9

header_pages:
  - index.md
#  - blog.html
  - about.md
  - contact.md

# footer: 'follow me on <a href="https://space.bilibili.com/18716770">bilibili</a>'

style: hacker

# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
