# Example Site settings

google_analytics: G-FG87FPT3X9

header_pages:
  - index.md
  - tags.md
  - about.md
  - contact.md

footer: &copy; 2024 Luc's cyber garden. All rights reserved.

style: hacker

# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
