# Example Site settings

# google_analytics: G-FG87FPT3X9

header_pages:
  - index.md
  - tags.md
  - about.md
  - contact.md

footer: <a href="https://info.flagcounter.com/Bn9w"><img src="https://s11.flagcounter.com/count2/Bn9w/bg_000000/txt_00FF00/border_000000/columns_4/maxflags_8/viewers_Hello+world/labels_0/pageviews_0/flags_0/percent_0/" alt="Flag Counter" border="0"></a>

style: hacker

# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
